@echo off
:crash
cd C:\Users\jayor\Desktop\AOP\finder
node randompd.js
cd C:\Users\jayor\Desktop\AOP
node dumbass.js
cd C:\Users\jayor\Desktop\AOP\finder
node mail.js
cd C:\Users\jayor\Desktop\AOP\finder
node randompd.js
cd C:\Users\jayor\Desktop\AOP
node dumbass.js
cd C:\Users\jayor\Desktop\AOP\finder
node mail.js
cd C:\Users\jayor\Desktop\AOP\finder
node randompd.js
cd C:\Users\jayor\Desktop\AOP
node dumbass.js
cd C:\Users\jayor\Desktop\AOP\finder
node mail.js
cd C:\Users\jayor\Desktop\AOP\finder
node randompd.js
cd C:\Users\jayor\Desktop\AOP
node dumbass.js
cd C:\Users\jayor\Desktop\AOP\finder
node mail.js
cd C:\Users\jayor\Desktop\AOP\finder
node randompd.js
cd C:\Users\jayor\Desktop\AOP
node dumbass.js
cd C:\Users\jayor\Desktop\AOP\finder
node mail.js